### ISSUE TITLE
Items deleted when stacked in Building UIs

### ISSUE THREAD

**Issue by Havanacus** [Minecolonies/minecolonies#317]
### Minecolonies version

minecolonies-universal-1.10.2-0.4.1870

Tested with
Forge 12.18.2.2179 (latest)
Forge 12.18.2.2123 (One I use)
Forge 12.18.2.2099 (Recommended)

### Expected behavior

- Adding items to a stack in a Building Inventory should increase stack size.

### Actual behaviour

- Stack size appears to increase, but interacting with stack sets in back to original value. Added items are lost.

### Steps to reproduce the problem

1. Put 16 dirt in Builder's Hut Inventory.
2. Add 10 more to that stack.
3. Stack displays 26.
4. Click stack to pick up.
5. You are the proud owner of 16 dirt.

**Comment by Raycoms** [comment]
Does that happen only on the server or in ssp as well?

**Comment by Havanacus** [comment]
I've only tested this in SSP.

I noticed while playing The Pilgrim Pack modpack, but tested in an instance with only Minecolonies before I posted.

**Comment by Raycoms** [comment]
Okay if it happens in ssp it happens in smp as well.
As soon as I'm done with the current issues. I'll take a look at this.
I've fixed that once already. Idk why it is back.

2016-12-08 13:47 GMT-02:00 Havanacus <notifications@github.com>:

**Comment by neadlak** [comment]
I was having this issue when using inventorytweaks sorting functions and shift-dragging to move things between containers. Lost a lot of fences/planks etc this way trying to restock builder huts.

**Comment by Raycoms** [comment]
Yeah, inventoryTweaks causing this isn't new to us.
But we didn't know about happening without using inventoryTweaks.

2016-12-08 21:25 GMT-02:00 neadlak <notifications@github.com>:

**Comment by SoulBrig** [comment]
I can confirm this on multiplayer server as well as singleplayer.  Disabled inventory tweaks in mod folder, but problem persists.  Shift-clicking anything stackable into Building Inventories will delete any items added to stack.  

Example Repro steps: 

1. Place 1 Dirt Block (or anything stackable) into Builders Hut Inventory (or another building inventory).

2. Shift click a stack of 1 or more from your inventory, all items shift-clicked from player inventory will be lost.

Variation from above report, after items are shift-clicked into the Building inventory, the stack size will increment for a split second then decrements back to original value.

I was not able to reproduce this behavior on the individual colonists inventories, shift clicking into their inventories works.

**Comment by Raycoms** [comment]
Found the error. Solved it. Next update will include this.

2016-12-09 0:53 GMT-02:00 SoulBrig <notifications@github.com>:
